### ISSUE TITLE
whereami doesn't bind to ipv6 addresses on dualstack clusters

### ISSUE THREAD

**Issue by gbrayut** [GoogleCloudPlatform/kubernetes-engine-samples#1006]
I believe `host='0.0.0.0'` [here](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/a47a452125bb2e3c3bc64e2b9443433550aaaa53/whereami/app.py#L190) results in an ipv4 only listener. I tried using the following for External Passthru NLB with ipv6 but because the container only binds to ipv4 it results in failed connections:

```
apiVersion: v1
kind: Service
metadata:
  name: whereami
  namespace: whereami
spec:
  ipFamilyPolicy: RequireDualStack
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: whereami
  type: LoadBalancer
```

Sounds like using '::' instead of '0.0.0.0' would bind to both, or you could add a HOSTS variable to allow configuration by end users
