### ISSUE TITLE
POSTGRES_DB_PASSWORD to POSTGRES_PASSWORD

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/kubernetes-engine-samples#116]
With Cloud SQL **Database version is PostgreSQL 11**, [the code line](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/3fcb2fe644f0a2bcf4b2b59663026e9481298424/cloudsql/postgres_deployment.yaml#L32) throws error 
`You must specify POSTGRES_PASSWORD to a non-empty value for the superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
`

code fix proposed to change from _POSTGRES_DB_PASSWORD_ to POSTGRES_PASSWORD, _POSTGRES_DB_USER_ to POSTGRES_USER

```
        - name: POSTGRES_DB_HOST
          value: 127.0.0.1:5432
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-user-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-user-credentials
```
