### ISSUE TITLE
I can connect my cloud sql instance from cloudsql-proxy

### ISSUE THREAD

**Issue by walteraa** [GoogleCloudPlatform/kubernetes-engine-samples#53]
Hi guys,

I follow the [official tutorial](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine) about using cloudsql proxy to connect my application and my app can't connect the database.

When I try to use the following command:
```
root@web-app-689b6bd75d-bwmxj:/var/www# mysql -h 127.0.0.1 -p 3306 -u proxyuser -p
```
And add my proxyuser password, or try to use another user added manually, I am getting the following error:

`ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0`

This is my yaml deployment:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: app
          image: gcr.io/potent-zodiac-172621/teste-app:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DB_DATABASE
              value: admin_teste
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=potent-zodiac-172621:southamerica-east1:teste-instance=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
```

It is important to note, that the MySQL port is hardcoded using the value 3306 in the application.

Could someone help me?
