### ISSUE TITLE
Provide a sample using Cloud Pub/Sub Notifications for Cloud Storage

### ISSUE THREAD

**Issue by anouarchattouna** [GoogleCloudPlatform/kubernetes-engine-samples#89]
Hello, is it possible to provide a sample using **Cloud Pub/Sub Notifications for Cloud Storage** ?

:white_check_mark: The [quotes app](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/service-catalog/cloud-storage) deals with storing and retrieving objects from **Cloud Storage**.
:white_check_mark: The [pub/sub app](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/service-catalog/cloud-pubsub) allows to publish messages, and then to receive the published messages from **Cloud Pub/Sub**.

But how to set up and use [Cloud Pub/Sub Notifications for Cloud Storage](https://cloud.google.com/storage/docs/reporting-changes) using **Service Catalog** :question: :thinking:

Is there any additional parameters to set in the **cloud-storage** **ServiceInstance** manifest 
```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: storage-instance
  namespace: storage-quotes
spec:
  clusterServiceClassExternalName: cloud-storage
  clusterServicePlanExternalName: beta
  parameters:
    location: us-central1
    bucketId: quotes-bucket
```
and/or **cloud-pubsub** **ServiceInstance** manifest 
```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: pubsub-instance
  namespace: pubsub
spec:
  clusterServiceClassExternalName: cloud-pubsub
  clusterServicePlanExternalName: beta
  parameters:
    topicId: quotes-bucket-topic
    ## what kind of additional parameters can go here ?
```
in order to add a notification configuration to a bucket that sends notifications to a pub/sub topic :question:

**Comment by ahmetb** [comment]
The examples you quoted are for Kubernetes Service Catalog. 

We have a sample on how to authenticate to GCP APIs. 

For the sample you mentioned, you should try ro find samples on Storage documentation. 
https://cloud.google.com/storage/docs/reporting-changes. It’s unlikely we’ll be able to have a sample for every possible GCP feature in GKE samples list.

**Comment by anouarchattouna** [comment]
That's it, **I'm looking for a sample for Kubernetes Service Catalog** !

As I mentioned, Storage already have this sample  [Cloud Pub/Sub Notifications for Cloud Storage](https://cloud.google.com/storage/docs/reporting-changes). My question was how to make it run in Service Catalog, what parameters to use ?

==> what parameters to use in the **ServiceInstance** manifest in order to add a notification configuration to a bucket that sends notifications to a pub/sub topic ?
==> what are the possible parameters ?
```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: storage-instance
  namespace: storage-quotes
spec:
  clusterServiceClassExternalName: cloud-storage
  clusterServicePlanExternalName: beta
  parameters:
    location: us-central1
    bucketId: quotes-bucket
    ## WHAT ARE THE POSSIBLE PARAMETERS THAT GOES HERE !!!!
```
